# Generated by Django 4.2.3 on 2023-08-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0005_alter_municipality_options'),
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='municipalities.municipality'),
        ),
    ]
