# Generated by Django 4.2.3 on 2023-08-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_sensor_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_community_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('pm25', 'PM2,5'), ('pm10', 'PM10'), ('rh', 'Relative humidity'), ('temp', 'Temperature')], max_length=8)),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.sensor')),
            ],
        ),
    ]
