# Generated by Django 4.2.3 on 2023-08-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0006_province_active'),
        ('observations', '0003_alter_sensor_sensor_community_id_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='municipalities.municipality'),
        ),
    ]
