# Generated by Django 4.2.3 on 2023-07-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='municipalit_name_b1f50d_idx'), models.Index(fields=['code'], name='municipalit_code_8cb870_idx')],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipalities.province')),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'ordering': ('province__name', 'name'),
                'indexes': [models.Index(fields=['name'], name='municipalit_name_513090_idx'), models.Index(fields=['code'], name='municipalit_code_183b94_idx'), models.Index(fields=['province'], name='municipalit_provinc_7da3c2_idx')],
            },
        ),
    ]
