# Generated by Django 4.2.3 on 2023-07-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='municipalities.province')),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'indexes': [models.Index(fields=['name'], name='municipalit_name_513090_idx'), models.Index(fields=['province'], name='municipalit_provinc_7da3c2_idx')],
            },
        ),
    ]
