# Generated by Django 4.2.3 on 2023-07-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('province__name', 'name'), 'verbose_name_plural': 'municipalities'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('name',)},
        ),
    ]
