# Generated by Django 4.2.3 on 2023-07-26 10:43

from django.db import migrations

def add_provinces(apps, schema_editor):
    Province = apps.get_model('municipalities', 'Province')

    Province.objects.bulk_create(
        [
            Province(code=20, name='Groningen'),
            Province(code=21, name='Fryslân'),
            Province(code=22, name='Drenthe'),
            Province(code=23, name='Overijssel'),
            Province(code=24, name='Flevoland'),
            Province(code=25, name='Gelderland'),
            Province(code=26, name='Utrecht'),
            Province(code=27, name='Noord-Holland'),
            Province(code=28, name='Zuid-Holland'),
            Province(code=29, name='Zeeland'),
            Province(code=30, name='Noord-Brabant'),
            Province(code=31, name='Limburg')
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_provinces)
    ]
