# Generated by Django 4.2.3 on 2023-07-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_add_provinces'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('code',)},
        ),
    ]
