# Generated by Django 4.2.3 on 2023-08-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0004_add_initial_municipalities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('province__code', 'name'), 'verbose_name_plural': 'municipalities'},
        ),
    ]
